### PR TITLE
stop progation on click event for filtering

### PR DESCRIPTION
**Pull request by mariodivece**
When applying custom styles to the grid, I came across an issue where click on the filter button would cause the click on the tr and thus sorting immediately before displaying the filter. Stopping the vent propagation on the filter button solves the issue.

### CODE REVIEW

**Comment by Muchiachio** [comment]
Do you have a repro? I don't see this happening on the web site and I already have short circuits on sorting.

**Comment by mariodivece** [comment]
I would need to spend quite a bit of time preparing a sample which I unfortunately don't have. If you feel it is already handled, then consider it a suggestion. Thanks for this awesome lib!

**Comment by Muchiachio** [comment]
Okay, will close for now, but if you have a repro (can fork of off example pages for faster repo) feel free to contact me through issues.

**Comment by mariodivece** [comment]
I published a sample here:

https://www.elitecars.mx/Cars

open Chrome's developer tools and remove the stopPropagation() call in your javascript source (mvc-grid.js) -- hopefully this helps you see the effect.

**Comment by Muchiachio** [comment]
It doesn't have filters though.

**Comment by Muchiachio** [comment]
I see what is going on, you probably changed the grid partial to render custom icon, you can achieve the same with font awesome classes on button itself, instead of creating additional `<i>` child and it will work.
```HTML
<button type="button" class="mvc-grid-filter fas fa-filter"></button>
```

**Pull request closed without merging**
