### PR TITLE
Fixed UsingFilterOptions rendering in EF Core 3.0

### PR DESCRIPTION
**Pull request by DanielStaroscik**

### CODE REVIEW

**Comment by Muchiachio** [comment]
Could you create and issue explaining what doesn't work?

**Comment by DanielStaroscik** [comment]
In my app after migration from .NET Core 2.2 to .NET Core 3.0 (and from EF Core 2.2 to EF Core 3.0)
I recieved many exceptions:
`An unhandled exception occurred while processing the request.
InvalidOperationException: Null TypeMapping in Sql Tree
Microsoft.EntityFrameworkCore.Query.RelationalSqlTranslatingExpressionVisitor+SqlTypeMappingVerifyingExpressionVisitor.VisitExtension(Expression node)`
in columns with this filtering method:
`grid.Columns.Add(m => m.Year).Titled("Year").Css("align-middle").UsingFilterOptions();`

Without `UsingFilterOptions()` everything works fine, so based on that I found that problem is inside that method.
I found out that EF Core 3.0 throws exceptions when it can't translate expression to SQL, so I adjusted LINQ expresions to be translatable to SQL.

**Comment by Muchiachio** [comment]
Merged in 1a530eb621dc1b97745b4ea8a05cea7e11870c43.

**Comment by DanielStaroscik** [comment]
I found that this statement in my last commit
`Select(x => x?.ToString() ?? "")`
can be simplified with that:
`.Select(x => x!.ToString())`

**Pull request closed without merging**
